apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: todos.todoexample.com
spec:
  group: todoexample.com
  version: v1
  names:
    kind: Todo
    plural: todos
  scope: Namespaced